.github/dependabot.yml
=> ROE-59 Create dependabot file

README.md
Not all information can be added yet.
=> ROE-60 Display startup information in the repository README file

spec/schema.json
https://companieshouse.atlassian.net/browse/ROE-81
* Adding the initial version of the swagger spec to cover our (currently empty) post endpoint
=> ROE-81 Adding initial version of the api swagger spec

pom.xml
Changing the pom back to use Java 11
=> ROE-53 Changing pom to use Java 11

routes.yaml
Routes.yaml needs the path updating after root path was added to the controller
=> ROE-53 Fix routes.yaml to have correct path

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/Address.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/Entity.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/OverseasEntitySubmission.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/Presenter.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
* Model classes added and annotated with mappings to JSON fields
* Parent model class added to controller POST method as a request
body parameter
=> Roe 149 add submission model

pom.xml, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/Address.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/Entity.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/OverseasEntitySubmission.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/Presenter.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/repository/OverseasEntitySubmissionsRepository.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
* Added Mongo persistence annotations to the model classes
* Added new service and repository classes
* Service called from the controller when end-point is invoked
=> ROE-150 Persist model data to the Mongo DB

pom.xml, routes.yaml, src/main/java/uk/gov/companieshouse/overseasentitiesapi/client/ApiClientService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/exception/ServiceException.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/TransactionInterceptor.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/TransactionService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ApiLogger.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/TransactionInterceptorTest.java
https://companieshouse.atlassian.net/browse/ROE-151
Adding transactionInterceptor to perform security checks via transaction-api 'get' and to supply the controller with the transaction specified in the url.
Also updated the endpoint path to include 'transactions'
branch name was incorrectly named, should have been roe-151
=> ROE-151 add transaction interceptor

pom.xml, spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/exception/SubmissionNotFoundException.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfigTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-206
Added the controller and stubbed the service to map the submission.
=> Roe 206 filings endpoint

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
=> ROE-135 Minor change to POST creation end-point

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-211
Added a validation endpoint that will return true if a submission is found for the id and a not found response if not.
=> Roe 211 validation status endpoint

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
* For now, just presenter and entity data is added by the service
* Unit test updated
=> ROE-230 Set submission data in the filing for CHIPS

pom.xml
To try and get sonar test coverage working - 
changing parent from companies-house-spring-boot-parent to companies-house-parent.
companies-house-parent is what we used previous projects but when I created pom I looked at a recent api that used ompanies-house-spring-boot-parent  but it seems that this isn't the way to go.
=> Fix - pom changes to get sonar coverage working

src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfig.java
=> ROE-227 Remove unused import

src/main/resources/application.properties
* New spring actuator config
* Ensures that the health end-point name adheres to the CH standard
=> ROE-55 Configuration of the health-check end-point

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/BeneficialOwnersStatementType.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnersStatementDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnersStatementDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java
https://companieshouse.atlassian.net/browse/ROE-286
Beneficial owners statement enum added to the Overseas entity model.
=> Roe 206 bo statement model

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/EntityDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/EntityDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java
https://companieshouse.atlassian.net/browse/ROE-398
Updated field: "public_register_name" to "register_name"
Added field: isOnRegisterInCountryFormedIn
=> ROE-168 Keep entity fields up to date

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
* Additional data now returned from OE filings end-point
* Unit test added
=> ROE-429 Submit BO Individual data to CHIPS

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerCorporateDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/BeneficialOwnerAllFieldsMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java
https://companieshouse.atlassian.net/browse/ROE-449
Updated "register_name" to "public_register_name" in corporate bo and would have done for corporate maaging officer but this is not present yet so updated it in the spec only.
=> ROE-449 Ensure register name has public prefixed

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-491
Ensure gov auth bo is included in the filing data.
=> ROE-491 Append government beneficial owner to filing data

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
* Additional data now returned from OE filings end-point
* Unit test added
=> ROE-478 Submit BO Corporate data to CHIPS

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/ManagingOfficerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/ManagingOfficerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/ManagingOfficerMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java
Jira Link
https://companieshouse.atlassian.net/browse/ROE-410
Change description
Adding the corporate managing officer data model and unit tests to cover it
=> ROE-410 adding corporate managing officer data model

pom.xml, spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/CostsController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/CostsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/CostsControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/CostsServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-554
Adding /costs endpoint 
* Updated api-sdk-java version to latest
=> ROE-554 Adding /costs endpoint

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-486
Inclide managing officer individual data in the filing service.
=> ROE-486 Include individual managing officer data in the filing service

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/CostsController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/CostsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/CostsControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/CostsServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-78
* Add logging to costs endpoint
* Add feature flag to enable payment integration (or not)
* removed 'variable payments' from costs data, not used in confirmation statement and can't see it used in the transactions-api so not sure what it is, safer to remove if payments are ok in Confirmation statement like that
=> ROE-78 Update costs endpoint and feature flag payments

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-501
Add statement alongside the benefical owner collections .
=> ROE-501 Include Beneficial Owner statement in Filing Service

src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/ApplicationConfig.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
* Filing description now set when getting filing details
* Unit test changes to check generated description
=> ROE-786 Add filing details for e-Mails

src/main/java/uk/gov/companieshouse/overseasentitiesapi/client/ApiClientService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ApiLogger.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-810
Adding payment reference and payment method into the data exported from the /filings endpoint so we can pass them into Chips
=> ROE-810 include payment info in filings data

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/BeneficialOwnersStatementType.java
* Two options removed from the spec and also the enum
=> ROE-853 Remove partial data options for BOs

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-979
Due diligence added to the filing model.
NB: Commits should say roe-979 not roe-980
=> ROE-979 Introduce due diligence to the filing service

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-1185
Work to remove payment feature flag "FEATURE_FLAG_ENABLE_PAYMENT_16052022" and all associated code
=> ROE-1185 removing payment feature flag and associated code

spec/schema.json
https://companieshouse.atlassian.net/browse/ROE-1231
Include validation for presenter in api schema.
=> ROE-1231 Add validation to schema for presenter

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntityDueDiligenceDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/AddressDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/PresenterDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/DateValidators.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationUtils.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1253
Validate each field in the someone else overseas entity due diligence model.
=> ROE-1253 Validate oe due diligence

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnersStatementValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnersStatementValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-310
One field based on an enum so added this to the existing parent validation.
=> ROE-310 BO Statement validation

spec/schema.json
https://companieshouse.atlassian.net/browse/ROE-1252
Update api with validation for due diligence.
=> ROE-1252 Api spec for OE Due Diligence

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/Country.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/UkCountry.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1181
Additional test and name changes required.
=> Roe 1181 Additional Improvements

spec/schema.json
Update spec for due diligence
Resolves [ROE-1249](https://companieshouse.atlassian.net/browse/ROE-1249)
=> Update spec for due diligence

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-384
Validation and testing for the corporate beneficial owner.
=> Roe 384 validate corporate beneficial officers

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerGovernmentOrPublicAuthorityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-386
Api validation gov bos.
=> ROE-386 BO gov api validation

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1312
Check no un-required data for public register in
Entity
Beneficial Owner Other
=> ROE-1312 No data should be supplied if not on register

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/DateValidators.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/DateValidatorsTest.java
* Checks added to due diligence validators to detect null dates
and new unit tests added
* New unit tests added to check null dates in BO objects (implementation
already correct)
* Some other minor refactorings - renaming of methods and variables, code
formatting
=> ROE-1325 Handle NULL and empty dates passed to API

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1255
Updating the Entity length validations from 4000 to 160
Legal Form  4000 -> 160
Governing Law  4000 -> 160
Name of Register  4000 -> 160
=> ROE-1255 Update Entity 4000 string lengths to 160

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1385
Ensure null officer lists do not cause an internal server npe error
=> ROE-1385 API validation empty MOs or BOs fires Null pointer

src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1385
=> ROE-1385 Missing UT assert statement

src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/TransactionInterceptor.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/TransactionService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/TransactionInterceptorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/TransactionServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-1398
Adding extra logging into the transaction service to try and shed light on intermittent failures when getting transaction in Staging env.
=> ROE-1398 Improving exception logging in transaction service

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java
* Validation implemented this field as mandatory but it needs to be optional. Now changed.
* Unit test updated.
=> ROE-1428 Overseas Entity Due Diligence date now optional

pom.xml, spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
=> Add cost resource to filing

pom.xml, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
https://companieshouse.atlassian.net/browse/ROE-1425
Used the gson library present in the project to get a readable list of errors in json format. Removed stack trace by setting the exception argument to null.
=> ROE-1425 List validation errors and remove stack trace

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
* Resume link added when initial POST request comes in to controller
* Service changes to create te link if 'save and resume' is active
* Unit test changes
=> ROE-1643 Add 'resume' link to transaction when new submission created

src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1684
Check length of dual nationality string in bo and mo individual data.
=> Roe 1684 duel nationality combined length

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/StringValidators.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerCorporateValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/PresenterDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1248
Regex update and removed OWASP comment
=> ROE-1248 Update regex to match what is in the web and accounts

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
[UAR-168](https://companieshouse.atlassian.net/browse/UAR-168)
Adding feature flag for ROE Update and remove
=> UAR-168: Add Feature flag for ROE Update and Remove

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/EntityDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/EntityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1706
Added field to dto and dao models and then the validation.
=> Roe 1706 public register jurisdiction update

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/DueDiligenceDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/EntityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/ManagingOfficerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntityDueDiligenceDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/PresenterDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/DueDiligenceMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/ManagingOfficerMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/OverseasEntityDueDiligenceMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/PresenterMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
* e-Mail addresses trimmed in the DTO when set
* Mapper tests and mocks updated to ensure that setter methods are trimming the values
* Tested in Postman
=> ROE-1675 e-Mail address trimmed when received by the API

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/EntityDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/EntityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/EntityMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1758
* Removed from DTO, DAO and schema
* Associated field validation removed
* Tests updated
=> ROE-1758 Remove entity name from entity data block

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1754
Add further validation line for invalid characters.
=> ROE-1754 - TL - aml number does not have valid character check

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/StringValidators.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/DueDiligenceMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/StringValidatorsTest.java
https://companieshouse.atlassian.net/browse/ROE-1755
=> ROE-1755 adding validation to due diligence to check it matches 'agree'

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/CostsController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/CostsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/CostsControllerTest.java
UAR-298 https://companieshouse.atlassian.net/browse/UAR-298
Add feature flag for update and return registration costs directly if false.
Temporary fix for refunds calling costs and loading document when schema changed incompatibly.
=> uar-298 add feature flag as refunds fix

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/NationalityValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/NationalityValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-1995
Moved blank checks away from common code and ensured that mandatory and optional fields are treated separately.
```
``` …
=> ROE-1995 - TL - Second nationality should be fully optional

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
[ROE-1980](https://companieshouse.atlassian.net/browse/ROE-1980)
Update the flag used to CHIPS Screens (when this code is required)
```
```
- types other …
=> change Filing service flag from Trusts CHS to CHIPS

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
https://companieshouse.atlassian.net/browse/UAR-366
Add Update Save and Resume feature flag to overseas-entities-api
```
``` …
=> UAR-366: Add Update Save and Resume feature flag

pom.xml, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoModelChangeTest.java, src/test/resources/application.properties, src/test/resources/overseas_entity_v_3_0.json
https://companieshouse.atlassian.net/browse/ROE-2072
* Test changed to use an in-memory Mongo DB into which JSON is inserted and then read back into the DAO model
* This represents how the service runs and errors match those seen in LIVE
* Test now specifically names and targets JSON created with version 3.0 of the model
* Trust JSON block included
```
``` …
=> ROE-2072 - TL - Improvements to the model structure change unit-test

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-377
Minimal partial validation for update save and resume wip.
```
```
- types other than `fix:` and `feat:` …
=> uar-377 minimal update partial validation

src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/MongoConfig.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/MongoConverters.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/converter/OverseasEntitySubmissionDaoConverter.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidator.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/overseasentitiesapi/configuration/MongoConfig.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoModelChangeTest.java
https://companieshouse.atlassian.net/browse/ROE-2073
Add new custom converter for the OverseasEntitySubmissionDao, this requires us to manually configure the mongo client and template in order to add the custom converters
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …
=> ROE-2073 add new dao custom converter

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-381
```
``` …
=> Set the update journey resume link

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerGovernmentOrPublicAuthorityDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerGovernmentOrPublicAuthorityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/DateValidators.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java
https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/481?modal=detail&selectedIssue=UAR-431&sprint=2781
Adding ceased date field to BOs in API, testing and validating as needed
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
=> Uar 431 ceased date field and validation roe api

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-2092
Removed statement check for partial validation
```
``` …
=> ROE-2092 - TL - Removed statement check for partial validation

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-146
Updated submitted email
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, …
=> UAR-146: Update submitted email

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/BeneficialOwnersStatementType.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/BeneficialOwnerStatementTypeTest.java
https://companieshouse.atlassian.net/browse/ROE-2092
Added equals ignore case in the statement enum find method.
```
``` …
=> ROE-2092 Fix payments button when statement is in upper case

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/UpdateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/UpdateDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java, src/test/resources/overseas_entity_valid.json
https://companieshouse.atlassian.net/browse/UAR-331
Add Update data model to overseas-entities-api so that requests from web which contain Update data model are saved in the DB
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
=> UAR-331: Resume Update journey

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
https://companieshouse.atlassian.net/browse/UAR-146
Type was being duplicated
```
``` …
=> Bugfix: UAR-146: Fix duplicated type

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/OEPublicDataRetrievalHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/OEPublicDataRetrievalHelperTest.java
https://companieshouse.atlassian.net/browse/UAR-400
- Api call and helper class to retrieve public OE data
```
``` …
=> UAR-400: Api call to retrieve public OE data and new helper class

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustDataDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidatorTest.java
[ROE-1596](https://companieshouse.atlassian.net/browse/ROE-1596)
Added API Validation for trust 'Tell us about the individual' page
```
```
- types other …
=> Added API Validation for trust 'Tell us about the individual' page

src/test/java/uk/gov/companieshouse/overseasentitiesapi/converter/DocumentTransformerFactoryTest.java
https://companieshouse.atlassian.net/browse/ROE-2020
* Test only failed during build-test-analyse phase of the pipeline (for some unknown reason)
* Factory instantiation and initialisation approach changed in an effort to fix this
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with …
=> ROE-2020 Fix issue with pipeline test failure

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidatorTest.java
[ROE-1596](https://companieshouse.atlassian.net/browse/ROE-1596)
Fix for the field date become interested person, it should be validated only if type is interested person
```
``` …
=> Fix for the field date become interested person

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java
ROE-1596
Corrected locality for service address
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, …
=> Corrected locality for service address

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerGovernmentOrPublicAuthorityDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/ManagingOfficerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/ManagingOfficerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/UpdateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerGovernmentOrPublicAuthorityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/ManagingOfficerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/ManagingOfficerIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/UpdateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerCorporateValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-133
```
``` …
=> uar-133 resigned on & ch references

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceDataBlockValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceDataBlockValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-2172
Split due diligence into verification with and without identity date and linked it to full and partial validation respectively.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can …
=> ROE-2172 - TL - Do not validate identity date for partial validation

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PublicDataRetrievalService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/PublicDataRetrievalServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-401
https://companieshouse.atlassian.net/browse/UAR-402
- Bugfix for catching 404 error for officers data and pscs data
```
``` …
=> UAR-402: Bugfix for throwing 404 errors for BO and MO data

pom.xml
=> fix: Update pom.xml for api-sdk-java to version 2.0.256

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalServiceTest.java
=> fix: UAR-409/410/411--Fix for 404 causing error

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/HashHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/HashHelperTest.java
https://companieshouse.atlassian.net/browse/UAR-413
Add the secure hash function used for ids in self links
```
``` …
=> uar-413 secure hash for ids

pom.xml, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/PublicPrivateDataCombiner.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/PublicPrivateDataCombinerTest.java
https://companieshouse.atlassian.net/browse/UAR-399
Created class PublicPrivateDataCombiner which contains HashMaps of the OE, MO, BO data
Here the keys are a hashed ID and the value is a Pair containing the Public Data on the right and the Private Data on the Left
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a …
=> UAR-413: Collate public and private data

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/BeneficialOwnerType.java
[ROE-2214](https://companieshouse.atlassian.net/browse/ROE-2214)
Changed "Interested Person" to "Interested_Person"
```
``` …
=> changed space to underscore for interested person

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PopulateUpdateSubmissionService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityChangeComparator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/PopulateUpdateSubmissionServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityChangeComparatorTest.java
=> UAR-416: Compare and calculate differences for OE data (Bug fixes)

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/CostsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/resources/application.properties
https://companieshouse.atlassian.net/browse/UAR-661
https://companieshouse.atlassian.net/browse/UAR-209
Updating payment cost to be £120 and stored under variable name OE02_COST
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
=> UAR-209/661: Configure update payment

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-530
Add Company number if the submission is Update, so that it can be processed in Chips
```
```
- types …
=> UAR-530: Set company number if Update submission

src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/commonmodels/CompanyIdentificationTest.java
=> UAR-580/CompanyIdentificationTest

src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelperTest.java
=> fix: UAR-580 Comparison with LocalDate now handles if Date contains time

src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelperTest.java
https://companieshouse.atlassian.net/browse/UAR-580
Natures of control could be in different order when comparing.
```
``` …
=> uar-580 natures of control can be reordered

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/BeneficialOwnerAddition.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/ManagingOfficerAddition.java
=> UAR-640: Add annotations to ignore null fields in JSON output

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/IndividualManagingOfficerCessation.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerCessationServiceTest.java
=> UAR-641: Small fix on model field naming

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/CorporateEntityBeneficialOwnerAddition.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/LegalPersonBeneficialOwnerAddition.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/IndividualBeneficialOwnerPsc.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/Psc.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerAdditionService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/IndividualBeneficialOwnerPscTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/OtherBeneficialOwnerPscTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/PscTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerAdditionServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-580
Action Date was not set and is not required.
Register location comparison was against country not place
Birth date should not be changeable.
Don't pass through anything if no public data to compare agains (and log error for now)
BO additions to use CompanyIdentification (as MO adds and BO changes already does)
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic …
=> uar-580 bo change fixes

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/CorporateManagingOfficerCessation.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/IndividualManagingOfficerCessation.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/ManagingOfficerCessation.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerCessationService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerCessationServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-592
Send officerName as an object so that the FirstName and LastName can be accurately shown in Chips for review by the OPS team
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
=> UAR-592: Send officerName as an object in MO cessations

src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelperTest.java
https://companieshouse.atlassian.net/browse/UAR-580
Fix address line mix up.
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, …
=> uar-580 fix address lines

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/Presenter.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/PopulateUpdateSubmission.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/PopulateUpdateSubmissionTest.java
=> UAR-737: Rename name field in Presenter class

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-616
Temporarily disabling Partial Validation in the update journey.
```
``` …
=> UAR-616: Temporarily disable partial validation for update journey

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/BeneficialOwnerAddition.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/CorporateEntityBeneficialOwnerAddition.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/CorporateManagingOfficerAddition.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/IndividualBeneficialOwnerAddition.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/LegalPersonBeneficialOwnerAddition.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-590
rename residentialAddress registeredOffice for Corp and Other BO additions.
```
```
- types other than …
=> uar-590 registeredOffice not residentialAddress

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerAdditionService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerAdditionServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-593
the api uses placeRegistered while chips side uses registerLocation.
Line up by making api use registerLocation for registerName
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can …
=> uar-593 change register place to location

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionService.java
=> UAR-590: Fix address issue

src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/PopulateUpdateSubmission.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/UpdateMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/PopulateUpdateSubmissionTest.java
https://companieshouse.atlassian.net/browse/UAR-790
Changed getMonth to getMonth value so we are receiving numbered month, also formatting day and month to include 0 if single digit.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE …
=> UAR:790 Changing Statement date logic to correct format

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesDataController.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesDataControllerTest.java
https://companieshouse.atlassian.net/browse/UAR-616
Use Overseas Entity submission id to find submission and use that to find email address.
Use feature flag
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of …
=> uar-616 use overseas entity submission & feature flag for OE details fetch

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/commonmodels/Address.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/commonmodels/AddressTest.java
https://companieshouse.atlassian.net/browse/UAR-591
This PR is to make sure that the comparison of the two addresses will still be equal in the following circumstances 
| Circumstance                                 | Example of 1st Address Line | Example of 2nd Address Line | equals() result |
| -------------------------------------------- | --------------------------- | --------------------------- | --------------- |
| The capitilisation is different              | "123 MAIN STREET"           | "123 Main Street"           | True            |
| The spacing is inconsistent                  | "123 &nbsp; &nbsp; &nbsp; Main &nbsp; &nbsp; Street" | "123 Main Street"           | True            |
|                                              | "123 Ma in Street"          | "123 Main Street" …
=> fix/UAR-591 Fixing Address Equals

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
=> UAR-587: Refactor validation for no change update scenario

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeServiceTest.java
When creating the ManagingOfficerChangeService and the BeneficialOwnerChangeService the data from the public/private data did not match what was in the Mapping ODP.
```
``` …
=> fix/UAR-594 Fixed mismatched service address issue

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-594
IgnoreCase for Names as they are stored in uppercase in CHIPS
```
``` …
=> UAR-594: Changes to ignoreCase for Names

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/Psc.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/NatureOfControlTypeMapping.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelperTest.java
=> fix/UAR-591 Registration Address issue and Nature of Controls Mapping

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-594
Change format for Ind MO name during comparison and ignoreCase for contact name and email
Response from public MO endpoint
Response from private MO endpoint
```
``` …
=> UAR-594: Changes for Ind Name and Contact

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/NationalityOtherMapping.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerChangeServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/NationalityOtherMappingTest.java
https://companieshouse.atlassian.net/browse/UAR-594
Change for Nationality appearing in a different format for MO
```
``` …
=> UAR-594: Nationality fix

src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/UserAuthenticationInterceptor.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/UserAuthenticationInterceptorTest.java
https://companieshouse.atlassian.net/browse/UAR-891 
New Implementation for the ROE Update Permissions See Jira Link for Details.
- [ Y] Tests added where applicable
```
``` …
=> ROE Update Service Permissions New Implementation

Makefile, pom.xml, suppress.xml
https://companieshouse.atlassian.net/browse/ROE-2300
make and pom files updated to include transitive dependency security analysis
```
```
- types other than …
=> ROE-2300 Security analysis checks

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
https://companieshouse.atlassian.net/browse/ROE-2303
Removed validation feature flag from controllers.
```
``` …
=> ROE-2303 Remove validation flags from the controller

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-711
Add back BO/MO validation
```
``` …
=> uar-711 add back bo/mo validation to full update

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
https://companieshouse.atlassian.net/browse/ROE-2304
Replaced body of the original create method with that of the start endpoint method and then removed the start method.
```
``` …
=> Roe 2404 remove start endpoint

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-2305
Remove create with resume method and replace original create method with the "with resume" method body.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of …
=> ROE-2305 Remove unused methods and refactor in service

src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/PopulateUpdateSubmission.java
https://companieshouse.atlassian.net/browse/UAR-938
Bug fix where aml number is not showing up in update submission due diligence for agent details.
Added aml mapping in update submission.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING …
=> Bug fix to map aml number for agent due diligence for update submissions

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-946
Fix entity name not being passed for no change.
```
``` …
=> uar-946 include entity number when no change

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-949 
Handle 404 more gracefully by returning OE details but with empty email address instead of service exception.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits …
=> uar-949 handle 404 for oe details fetch gracefully

pom.xml
=> UAR-617: Update version number of private-api-sdk-java

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java
https://companieshouse.atlassian.net/jira/software/c/projects/UAR/boards/531?modal=detail&selectedIssue=UAR-1094&sprint=3028
Fixes the issue where service address was left blank in the json output when service address was the same as registered/principal address
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking …
=> BUGFIX: UAR-1094: Fix trust addresses

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/UpdateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/UpdateDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java
https://companieshouse.atlassian.net/browse/UAR-1063
add trusts to update model. For review and no change loading.
```
``` …
=> uar-1063 add review trusts to update model

src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoModelChangeTest.java, src/test/resources/overseas_entity_v_3_1.json
https://companieshouse.atlassian.net/browse/ROE-2343
Update the v_3_1 test json with some fields that were missing
```
``` …
=> ROE-2343 Update some of the missing json fields for v_3_1 json

src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoModelChangeTest.java, src/test/resources/overseas_entity_v_3_1.json
https://companieshouse.atlassian.net/browse/ROE-2343
Adding more missing data to the overseas_entitiy_v_3_1.json test file
```
```
- types other than `fix:` …
=> ROE-2343 Updating v_3_1 model test json with missing data

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustCorporateValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-1094
Validation was failing as service address not being returned as empty. The check is no longer needed as it's ensured by the model that the service address is same as.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …
=> uar-1094 fix trustee service address validation

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/UpdateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustDataDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustDataToReviewDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustReviewStatusDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/UpdateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustDataToReviewDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustReviewStatusDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/TrustMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java, src/test/resources/overseas_entity_v_3_1.json
https://companieshouse.atlassian.net/browse/UAR-109
Associated changes in web requiring this change:
- https://github.com/companieshouse/overseas-entities-web/pull/1065
Added 'review' meta data to trust model.
=> UAR-109: Add review object to Trusts-in-review model

src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfig.java
=> UAR-1145: Fix routing

pom.xml, routes.yaml, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/TrustsDataController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/TrustsDataControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-1146
UAR-1146 Retrieve Individual Trustee Private Data
=> UAR-1146 Individual Trustee Private Data

pom.xml
=> UAR-1147: Updated pom.xml

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-1142
fix code smell
=> remove code smells

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustReviewStatusDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustReviewStatusDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/TrustMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java, src/test/resources/overseas_entity_v_3_1.json
https://companieshouse.atlassian.net/browse/UAR-263
Added a new field to review status to better indicate if the details about the trust itself have changed
- api-sdk-node pr: https://github.com/companieshouse/api-sdk-node/pull/621
=> UAR-263: Added another property to trust review status for trust details

src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfig.java
https://companieshouse.atlassian.net/browse/UAR-1187
add individual trustees endpoint to interceptor config
```
``` …
=> uar-1189 add individual trustees enpoint to interceptor config

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/ManagingOfficerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/ManagingOfficerIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/IndividualBeneficialOwnerCessation.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/IndividualManagingOfficerCessation.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerCessationService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerCessationService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java, src/test/resources/overseas_entity_v_3_1.json
https://companieshouse.atlassian.net/browse/UAR-1198
Add a have day of birth flag to individual BOs and individual MOs in a backwards compatible manner.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any …
=> uar-1198 add have day of birth flags

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/TrustsDataController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/HashHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesDataControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/TrustsDataControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/HashHelperTest.java
https://companieshouse.atlassian.net/browse/UAR-1187
Refactor HashHelper instantiation
```
``` …
=> UAR-1187: Refactor HashHelper instantiation

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/TrustsDataController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/HashHelper.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/HashHelperTest.java
https://companieshouse.atlassian.net/browse/UAR-1187
fix for hash helper init problem
```
``` …
=> uar-1187 fix hashhelper init

pom.xml
=> fix/UAR-1190 private-api-sdk update

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-1218
```
``` …
=> UAR-1218: Update statement validation

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidatorTest.java
=> FIX:UAR-1218: Tidy up comments

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidatorTest.java
=> UAR-1218: Small fix to logic

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/IndividualBeneficialOwnerCessation.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/CorrespondenceAddressChange.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/EntityEmailAddressChange.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/EntityNameChange.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/PrincipalAddressChange.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PublicDataRetrievalService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidator.java
https://companieshouse.atlassian.net/browse/UAR-892
Small changes to reduce the number of code smells, which can be found here:
https://code-analysis.platform.aws.chdev.org/dashboard?id=uk.gov.companieshouse%3Aoverseas-entities-api
The code smell on line 139 of `OverseasEntitySubmissionDtoValidator` which is commented out code has been kept on request as it will be used in another ticket
```
```
- feat: a commit that introduces a new feature to the codebase (this …
=> UAR-892: Fix Code Smells

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-1251
```
``` …
=> UAR-1251: Implement trust validation

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-897
Re-add partial validation for update journey and tighten statement validation
```
```
- types other than …
=> UAR-897: re-add partial validation, update statement validation

src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-897
Fix test to not expect partial validation to call entity validation.
```
```
- types other than `fix:` …
=> uar-897 fix partial test to not expect entity validation to be called

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/SchemaVersion.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoModelChangeTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1326
* Save value to Mongo if present in the received JSON data
* Define a new model version (for Remove changes)
* Update appropriate unit tests
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
=> UAR-1326 Add a new 'is_remove' field to the OE Mongo data

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
https://companieshouse.atlassian.net/browse/UAR-1369
* Additional logging will hopefully help diagnose a LIVE issue
* Should indicate whether 'due diligence' data is submitted in the filing
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING …
=> UAR-1369 Add new log statements

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/RemoveDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/RemoveDto.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1281
* New field added to DTO and DAO
* New container DTO and DAO classes added for the remove fields
* Test JSON updated to have the new container and field
```
``` …
=> UAR-1281 Add new field to capture the confirm removal statement acceptance

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/CostsController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesDataController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/TrustsDataController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/CostsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/SubmissionType.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/CostsControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesDataControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/TrustsDataControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/CostsServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java, src/test/resources/application.properties
https://companieshouse.atlassian.net/browse/UAR-871
* Refactoring of Costs controller and tests
* New Costs service implementation for Remove
* DTO helper method changes to determine which journey is being followed
* Checks for appropriate journey when processing updates and removes
* TODO comments added where work needs to be done for Remove (validation and filing)
* Miscellaneous unit test changes
```
```
- feat: a commit that introduces a new feature to the codebase …
=> UAR-871 Implementation of payments and costs for Remove

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/RemoveValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/RemoveMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/RemoveValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-1414
partial API Validation - Confirm the removal statement page
```
``` …
=> uar-1414-partial API Validation - Confirm the removal statement page

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/UpdateSubmission.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java, src/test/resources/application.properties
https://companieshouse.atlassian.net/browse/UAR-1445
* Refactored Update code to allow for use by Remove
* Some minor code and formatting improvements
* New unit test added for the remove submission
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
=> UAR-1445 Changes to submit filing data for the Remove journey

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/RemoveValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/RemoveValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-1461
Added common validation checks already present in update
Introduced check for the update filing date and return a 400 error when it is present.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
=> UAR-1461 Partial API Validation of Remove Data

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustDataDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustDataDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/DateValidators.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/DateValidatorsTest.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1432
* New DTO and DAO fields with getters and setters defined
* Trust validation logic refactored and extended to check the new field
* Unit tests added and updated
```
``` …
=> UAR-1432 Support for adding a ceased date to trusts

src/test/resources/application.properties
[FEE-39](https://companieshouse.atlassian.net/browse/FEE-39)
[FEE-41](https://companieshouse.atlassian.net/browse/FEE-41)
[FEE-43](https://companieshouse.atlassian.net/browse/FEE-43)
[FEE-39]: https://companieshouse.atlassian.net/browse/FEE-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEE-41]: https://companieshouse.atlassian.net/browse/FEE-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEE-43]: https://companieshouse.atlassian.net/browse/FEE-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- update OE form fees
We are committed to keeping commit history clean, consistent and linear. To achieve this, this commit should be structured as …
=> fee-39-41-43: update oe fees

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesDataController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/TrustsDataController.java
https://companieshouse.atlassian.net/browse/ROE-2550
* Inability to find data required by trusts now logged at the correct level and matches what is done by the OE web service
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
=> ROE-2550 Change log level from ERROR to INFO

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
https://companieshouse.atlassian.net/browse/UAR-1302
* Flag was present and set but never used. All traces now gone.
```
``` …
=> UAR-1302 Remove the ROE Remove feature flag

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/RelevantStatementsType.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/UpdateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/UpdateDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/RelevantStatementsTypeTest.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/ROECCT-149
```
``` …
=> ROECCT-149 - Changes to Mongo DB

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustDataDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustDataDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/TrustMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoModelChangeTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidatorTest.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1511
Review the trust page containing question "is the trust still involved in the overseas entity" - when BOs are still attached to trusts the response to the question will be checked in the form of a flag passed to the api.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces …
=> UAR-1511 API Validation - Review the trust page containing question

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1520
- New DTO and DAO fields with getters and setters defined
- Json test file updated.
```
```
- types …
=> UAR-1520 Support for adding ceased date to individual trustees

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/UpdateSubmission.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/PopulateUpdateSubmission.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/UpdateMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/PopulateUpdateSubmissionTest.java
https://companieshouse.atlassian.net/browse/ROECCT-143
```
``` …
=> Update Filing Service for Relevant Period new Statements

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/DateValidators.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidatorTest.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1516
API validation to be applied to any data related to the 'Individuals involved in the trust? page 
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any …
=> uar-1516 add validation to review trust individual trustee page

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerGovernmentOrPublicAuthorityDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/ManagingOfficerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/ManagingOfficerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerGovernmentOrPublicAuthorityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/ManagingOfficerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/ManagingOfficerIndividualDto.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1402
Ids were not being saved to Mongo when BOs and MOs moved out of review on an Update/Remove journey. This then caused various issues if the submission was saved and later resumed. Ids are now persisted by the OE API, allowing things to work as expected.
```
```
- BREAKING CHANGE: a commit that has a …
=> UAR-1402 Update save and resume ids for BOs and MOs

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/HistoricalBeneficialOwnerDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/HistoricalBeneficialOwnerDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1400
Add missing trust sub-entities ids in MongoDB
```
```
- types other than `fix:` and `feat:` are allowed, …
=>  uar-1400 add ids to trust sub entities

Tiltfile.dev
The image path was updated in the docker config but was missed in the tilt file causing local changes not to be picked up. 
```
```
- types other than `fix:` …
=> Update tiltfile image name to match that used in docker config

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/ROE-2567
* Model and DAO changes to add the new field
* New validation logic added (only run if new API Redis feature flag is true)
* Swagger schema spec updated
* Unit tests added and amended
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating …
=> ROE-2567 Persist and validate a new 'has sold land' field

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidatorTest.java
https://companieshouse.atlassian.net/browse/UAR-1508
* Validation check now made and error reported if no BOs are assigned
* Unit test added
```
```
- types …
=> UAR-1508 Check BOs assigned to trust for a Registration submission

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerGovernmentOrPublicAuthorityDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustDataDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerGovernmentOrPublicAuthorityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustDataDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/BeneficialOwnerAllFieldsMock.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/TrustMock.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/ROECCT-228
```
``` …
=> ROECCT-228- Flag for each object added for pre-registration period

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-2573
Move /transactions/{TRANSACTION_ID_KEY}/overseas-entity/start logic and remove the endpoint
- move logic from createNewSubmissionForSaveAndResume to createNewSubmission
- remove createNewSubmissionForSaveAndResume
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a …
=>  roe-2573 update createNewSubmission

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustCorporateDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/TrustMock.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/ROECCT-245
```
``` …
=> ROECCT-245 -Add new field for legal entity beneficiaries to indicate became dates

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalService.java
https://companieshouse.atlassian.net/browse/UAR-1594
Added some additional logging statements to make it clear if private BO data could not be retrieved for some reason.
```
``` …
=> UAR-1594 Additional logging added when retrieving BOs

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/TrustMock.java, src/test/resources/overseas_entity_v_3_2.json
=> ROECCT-233 - add new field for beneficiaries to indicate became dates

ecs-image-build/Dockerfile
https://companieshouse.atlassian.net/browse/UAR-1594
```
``` …
=> enforce utf-8 encoding

pom.xml
Updating the docker image to shared services image before deployment to Staging.
```
``` …
=> updating docker image to shared-services

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerGovernmentOrPublicAuthorityDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerIndividualDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerGovernmentOrPublicAuthorityDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerIndividualDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1610
Similar to and using the changes in:
https://github.com/companieshouse/ecs-service-configs-dev/pull/621
updated the model and validator with the three new fields.
```
``` …
=> UAR-1610 Introduce new nocs to GPA BO and validate

spec/schema.json, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerCorporateDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerCorporateDto.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidator.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/NatureOfControlValidators.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidatorTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java, src/test/resources/overseas_entity_v_3_2.json
https://companieshouse.atlassian.net/browse/UAR-1614
Added the new noc fields:
"non_legal_firm_control_nature_of_control_types";
"trust_control_nature_of_control_types";
"owner_of_land_person_nature_of_control_jurisdictions";
"owner_of_land_other_entity_nature_of_control_jurisdictions";
along with validation and schema updates.
```
```
- BREAKING CHANGE: a …
=> Uar 1614 ole bo new nocs

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionService.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeService.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionServiceTest.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeServiceTest.java
https://companieshouse.atlassian.net/browse/UAR-1608
Updated the additions and changes service to include the corporate bo.
```
```
- types other than `fix:` …
=> UAR-1608 Add nocs to corporate bo update journey

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf
[JU-892](https://companieshouse.atlassian.net/browse/JU-892)
- Remove healthcheck path from lb listener paths
```
```
- types other than `fix:` and `feat:` …
=> FIX: platform tech debt

terraform/groups/ecs-service/main.tf
https://companieshouse.atlassian.net/browse/JU-892
Update var
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, …
=> add read_only_root_filesystem var

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/PaymentDao.java, src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/PaymentDto.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/PaymentMock.java
=> ROEECT-Payment Support with API Changes

src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/ProcessingInterceptor.java, src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/ProcessingInterceptorTest.java
https://companieshouse.atlassian.net/browse/ROE-2732
Added force flag accepting logic in processing interceptor for accepting the request 
PUT and GET requests
- [ X] Tests added where applicable
=> Accepting force flag with PUT and GET requests for payment data

pom.xml
https://companieshouse.atlassian.net/browse/ASM-500
Add latest Sonar config to Pom
```
``` …
=> ASM-500 Add new sonar config to pom

README.md
https://companieshouse.atlassian.net/browse/ASM-500
Remove blank line to trigger sonar
```
``` …
=> ASM-500 remove blank line to test sonar

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> feat: tech debt changes

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/variables.tf
Reverts companieshouse/overseas-entities-api#461
=> Revert "test: bump resources"
