companieshouse/overseas-entities-api

pom.xml

* java 11 requires the config to set JAVA_HOME to the java 11 directory, overriding the environment default
* reverting back to java 8 until we get guidance on correct version

ROE-53 Changing pom to use java 8

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/OverseasEntitiesApiApplication.java

* Done in order to correctly handle BST when persisting date-times in Mongo

ROE-140 Set UTC time-zone

---

pom.xml
src/main/java/uk/gov/companieshouse/overseasentitiesapi/client/ApiClientService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/exception/ServiceException.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/TransactionService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/TransactionServiceTest.java

https://companieshouse.atlassian.net/browse/ROE-151
In order to add the transaction interceptor we need to add the TransactionService which also uses the ApiClientService (to manage the sdk access)
This adds the TransactionService and ApiClientService

ROE-151 Adding TransactionService and ApiClientService

---

pom.xml

Sonar is not reporting unit test coverage, possibly caused by jacoco version missing from pom. Adding it to try and resolve issue.

Fix - adding jacoco version to try and get test coverage working

---

spec/schema.json

https://companieshouse.atlassian.net/browse/ROE-256
Updating schema spec to include the data structure for beneficial owners and managing officers
The nature of control options on the V4 prototype are check boxes where you can select more than one, so have set the nature of controls to be arrays.

ROE-256 add beneficial owner spec

---

spec/schema.json

https://companieshouse.atlassian.net/browse/ROE-285
Adding the beneficial owners statement to the api spec

ROE-285 Adding beneficial owners statement to api spec

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java

* Presenter details no longer sent (at present) as there is no
defined home yet in the CHIPS form XML

ROE-212 Changes to initial CHIPS filing

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java

https://companieshouse.atlassian.net/browse/ROE-552
Add the costs link to the transaction resource for overseas-entity.
This will mean that when closing the transaction, a link to the payment service will be provided for us by the transactions-api.

ROE-552 Add costs link to the transaction resource

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java

https://companieshouse.atlassian.net/browse/ROE-78
Removing the resource costs link temporarily to disable payment service integration as Toro1 is unable to send transactions to chips until payment integration is complete

ROE-78 Disable payment integration

---

routes.yaml

* Will now allow access to the healthcheck end-point via ERIC
and not return a 404 'not found' status code

Simple 'routes' config change

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/client/ApiClientService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsController.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/FilingsControllerTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java

https://companieshouse.atlassian.net/browse/ROE-810
Fix for issue that was occurring in ci-dev where we were getting a 401 not authorised  when trying to get the payment info from the transaction api. I think it is related to the apiClient call I introduced (taken from confirmation statement), but confirmation-statement-api has it's own chs key defined with internal app privs. As it looks like whatever calls the /filings endpoint is an internal app, i'll use the apiClient call that passes the eric header info across, so hopefully the calling app privileges will be passed through to the transactions-api and payment-api so we can get the payment data.

ROE-810 Fix permission issue when getting filings payment info

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/OverseasEntitiesApiApplication.java

* A new custom JSON object mapper bean was added for trusts
but this is now also the default used when mapping JSON objects
in the controller API methods. Change made to ensure that the
new mapper ignores any unknown properties (which was the case
previously, with the default mapper)

Ignore unknown JSON properties when mapping

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/OverseasEntitiesApiApplication.java

* A new custom JSON object mapper bean was added for trusts
but this is also the default used when mapping JSON objects
in the controller API methods. It was causing further issues
and it actually isn't required - auto-wiring within the filing
service still works (tested using Docker) - and has therefore
been removed.

Remove the new (not required) mapper bean

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/BeneficialOwnerType.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/AddressDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustCorporateDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java

Fix some issues found when sending the trust_data to the chips-filing-consumer
- Fix Settlor spelling mistake
- Make `type` of trustee not case sensitive
- Make address fields and trust fields optional
Resolves: ROE-989

Make address fields optional

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/exception/GlobalExceptionHandler.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ApiLogger.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/exception/GlobalExceptionHandlerTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/ApiLoggerTest.java

https://companieshouse.atlassian.net/browse/ROE-1095
Add a generic exception handler to intercept uncaught exceptions and log them using Structured logger, so that the message gets a namespace for it to appear in Kibana logs

ROE-1095 Add global exception handler

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustCorporateDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustIndividualDto.java

Currently if a postcode isn't included in an address for a trust then it doesn't save the address. This creates a more generic address check to see if any address fields are populated. 
Resolves: ROE-1164

Change postcode check on trust addresses to allow addresses

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/AddressDtoValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/Country.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/UkCountry.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1181
When a uk country id added for due diligence validation will cause this to fail as uk countries are not on the countries list so added a condition that will allow due diligence to skip this check.

Roe 1181 Uk countries required as valid

---

spec/schema.json
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/Country.java

https://companieshouse.atlassian.net/browse/ROE-1254
Removed province of China form Taiwan.

ROE-1254 Revert the name change for Taiwan

---

src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityDueDiligenceValidatorTest.java

Dates in unit tests can come back to haunt to added a an ensured past date in the before each code.

ROE-1181 Avoid unexpected test failure with test dates

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/AddressDtoValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/StringValidators.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/UtilsValidators.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1311
Validation has to ensure that flag controlled information is not unnecessarily passed into the api when it is not expected, in this case when the same address flag is true for entity and all B.Os, the service address is empty.
From looking at the web an empty Service address and never a null one is passed into the api.

ROE-1311 No service address when same as flag is true

---

spec/schema.json
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/PresenterDtoValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/PresenterDtoValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1247
Updated max length. Avoided extracting this to a constant in case the criteria change again and the values need to be different.
Updated the unit tests for this functionality and updated the code to match the latest in other unit tests.

ROE-1247 Update max length validation for presenter

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityDtoValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1257
Work to update the entity email field max length validation from 250 to 256 characters

ROE-1257 Updating entity email max length validation to 256

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java

https://companieshouse.atlassian.net/browse/ROE-1378
Changing the OverseasEntitiesController to add any validation messages into the response body so the user can see what has failed validation without having to look in the logs

ROE-1378 Add validation failure messages to response body

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java

https://companieshouse.atlassian.net/browse/ROE-1442
Adding new temporary POST endpoint to handle the initial 'partial' data from first data screen
**/transactions/{TRANSACTION_ID}/overseas-entity/start**
This will eventually become **/transactions/{TRANSACTION_ID}/overseas-entity**  once we have all the save and resume work completed.
This is so not to complicate matters with the existing POST endpoint which validates a whole submission.
New endpoint currently has no validation but will be added by https://companieshouse.atlassian.net/browse/ROE-1415

ROE-1442 add new post endpoint for save and resume

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/DueDiligenceValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1510
Extra check added to the anti-money laundering number to test whether the field is null so the correct http number and error message are returned.

ROE-1510 Return correct error when aml number is null

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/exception/GlobalExceptionHandler.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/exception/GlobalExceptionHandlerTest.java

https://companieshouse.atlassian.net/browse/ROE-1447
The GlobalExceptionHandler will now encode and truncate exception messages and stack traces so that if any json parse errors occur, the original value will be encoded and the stack trace truncated before logging.

ROE-1447 sanitise exceptions in global exception handler

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java

* Calling the 'validation-status' end-point when API validation is enabled now invokes the full set of checks
* An error is added to the response if any checks fail
* Unit tests added and updated

ROE-1426 Run all validation checks when transaction is closed

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1629
Set validation logic to be !(A || B) to allow BOs and MOs to be added in any order.

ROE-1629 Enable submission of MOs for Some Identified Statement

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OwnersAndOfficersDataBlockValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1649
Existing validation renamed to "validationFull" and this verifies the bo and mo list against the beneficial_owners_statement.
New validation method "ValidationPartial" this just check the content of each block but not the submissions as a whole.
We need to make sure we call /start otherwise validationFull will be called and a partial submission will fail with an NPE if there is no overseasEntitySubmissionDto.

ROE-1649 API Implement partial submission validation

---

spec/schema.json
src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/exception/SubmissionNotLinkedToTransactionException.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/EntityMock.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java

https://companieshouse.atlassian.net/browse/ROE-1645
New controller, calls service and in the service:
Check user associated with the supplied transaction - added note to the ticket -link to code in transactions api.
Check supplied transaction relates to the supplied OE id as done in the pUT endpoint.
Obtains the submission from mongo and check submission is not empty.

ROE-1645 Add a GET endpoint to retrieve submission data

---

spec/schema.json
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/BeneficialOwnerIndividualDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/ManagingOfficerIndividualDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/BeneficialOwnerIndividualDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/ManagingOfficerIndividualDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/StringValidators.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/StringValidatorsTest.java

https://companieshouse.atlassian.net/browse/ROE-1543
https://companieshouse.atlassian.net/browse/ROE-1603
Updated:
- model
- validation
- spec
- unit tests
Added a separate field for the second nationality as the emphasis is on "dual" nationality not multiple nationalities it is a single field rather than a list. Followed what we do with former names.
Moreover, as this is not determined by a radio but just an extra field, a simple null check has been added a a condition for checking validation making this an optional field.

ROE-1543/1603 Include a second nationality in the model and validation

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfig.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/AbstractClosedTransactionInterceptor.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/FilingInterceptor.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/ProcessingInterceptor.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/UserAuthenticationInterceptor.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/configuration/InterceptorConfigTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/ProcessingInterceptorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/TransactionInterceptorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/UserAuthenticationInterceptorTest.java

https://companieshouse.atlassian.net/browse/ROE-1646
* Required for 'save and resume' but this safety check was missing off OE API end-points that had already been delivered
* Any end-points invoked from the web app (see URL patterns used in the implementation) now check that the associated transaction is not already 'Closed'. If it is, an error is returned to the client
* Achieved using a new 'ProcessingInterceptor'
* More generally, changed log output to use the ERROR level if an interceptor is about to fail the request
* Added unit tests for the new interceptor
* Updated some existing tests to improve on the checks that they were doing

ROE-1646 Do not allow certain operations on 'Closed' transactions

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java

https://companieshouse.atlassian.net/browse/ROE-1772
Updated the filing data and tests with the new entity name field.
Removed existing entity name from the tests.

ROE-1772 Use entity name in the filing data

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/AbstractTransactionStatusInterceptor.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/FilingInterceptor.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/ProcessingInterceptor.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/ProcessingInterceptorTest.java

https://companieshouse.atlassian.net/browse/ROE-1778
* Filing interceptor works as before, but implementation changed slightly in that class now takes ownership of checking the transaction status as well as handling it
* Processing interceptor implementation changed in a similar way and now also only allows requests against OPEN transactions
* New processing interceptor tests added
[ROE-1778]: https://companieshouse.atlassian.net/browse/ROE-1778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ROE-1778 Only allow updates against

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/client/ApiClientService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/TransactionService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/TransactionServiceTest.java

https://companieshouse.atlassian.net/browse/ROE-1828
* Company name set as current OE name on the Mongo transaction record when OE is initially created (API POST call) and each time that OE is updated (API PUT call)
* Internal API key client used for update calls to avoid 403 forbidden error when transactions API calls back into OE API
* Unit tests added and updated

ROE-1785 Update company name on Mongo Transaction record

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/AbstractTransactionStatusInterceptor.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/FilingInterceptor.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/ProcessingInterceptor.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/TransactionUtils.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/interceptor/ProcessingInterceptorTest.java

https://companieshouse.atlassian.net/browse/ROE-1925
* Required for 'Save & Resume' when 'Pay now' link clicked from 'Your filings' screen - web client needs to be able to retrieve OE submission data
* GET calls to retrieve data and also check validation status are now allowed if status of transaction is 'closed pending payment'
* Unit tests added/changed to check new behaviour

ROE-1925 -  TL - Allow GET calls when transaction 'closed pending payment'

---

spec/schema.json
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/EntityNameDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/EntityNameDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityNameValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/EntityNameMock.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/Mocks.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/EntityNameValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1946
- Updated model to change entity name from a field to a block object.
- Added separate verification for entity name.
- Updated spec
- Ensure partial validation returns an error when the entity name field in the block is explicitly null but not when the block is absent.
- Null checks for entity name in the OverseasEntitiesService and the FilingsService.

Roe 1946 - TL - handle new entity name block

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/NationalityValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/BeneficialOwnerAllFieldsMock.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/ManagingOfficerMock.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/ManagingOfficerIndividualValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/NationalityValidatorTest.java

https://companieshouse.atlassian.net/browse/ROE-1995
Added list of nationalities copied from what is present in the webapp.
Invalid character validation no longer required.
Length and same nationality validation still required when a second nationality is added.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking …

ROE-1995 - TL - Nationality validation has not been implemented with a list

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/HistoricalBeneficialOwnerDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/HistoricalBeneficialOwnerDto.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/TrustMock.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java

[ROE-1919](https://companieshouse.atlassian.net/browse/ROE-1919)
This is part of a set of changes to allow former beneficial owners to be either individual (the current situation with the Trusts spreadsheet) or corporate (new and the data will only be set via the CHS Trust web pages).
See also [Change E2E design note](https://companieshouse.atlassian.net/wiki/spaces/TS/pages/4051108053/Changes+to+the+Historical+Beneficial+Owners+BO+Trustee+type)
```
```
- feat: a commit …

Allow historic BO to be corporate as well as individual

---

spec/schema.json
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/SchemaVersion.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/Constants.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntitiesServiceTest.java

https://companieshouse.atlassian.net/browse/ROE-2071
New enum to list schema versions.
New field typed by this enum in the submission model at the top level
Current schema number is kept as a constant.
Logging updated to specify version.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating …

Roe 2071 schema version field

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/trust/TrustCorporateDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/trust/TrustCorporateDto.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/TrustMock.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoDaoMappingTest.java

[ROE-2082](https://companieshouse.atlassian.net/browse/ROE-2082)
Add is_on_register_in_country_formed_in for Corporate Trustee
Tested locally with both new CHS Trust flags and spreadsheet (details in Jira)
```
``` …

Add new field onRegisterInCountryFormedIn for corporate trustees

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/MongoConfig.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/configuration/MongoConverters.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/converter/OverseasEntitySubmissionDaoConverter.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/DtoModelChangeTest.java

https://companieshouse.atlassian.net/browse/ROE-2100
* JVM warning no longer displays when performing a default model conversion
* Default mapping context (as opposed to a new one) now used when creating the new default converter
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with …

ROE-2100 Fix the warning shown when converting

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/DateValidators.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerCorporateValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerGovernmentOrPublicAuthorityValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/BeneficialOwnerIndividualValidatorTest.java

https://companieshouse.atlassian.net/browse/UAR-464
Remove check that cease date is not the same day as the appointed/start date for BO's (all 3 types)
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any …

UAR-464: Allow cease date to be the same as appointed date for BO's

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/converter/DocumentTransformerFactory.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/converter/DocumentTransformerFactoryTest.java

https://companieshouse.atlassian.net/browse/ROE-2020
* Test failure due to static declaration of the transformer map AND order in which tests ran
* 'static' modifier removed and helpful log message added
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). …

ROE-2020 Fix issue with pipeline test failure

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustCorporateValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustCorporateValidatorTest.java

[ROE-1597](https://companieshouse.atlassian.net/browse/ROE-1597)
In TrustCorporateValidotor.validateIdentificationlegalAuthority changed TrustCorporateDto.IDENTIFICATION_LEGAL_FORM_FIELD to TrustCorporateDto.IDENTIFICATION_LEGAL_AUTHORITY_FIELD
In testErrorReportedWhenLegalAuthorityIsNull and
testErrorReportedWhenLegalAuthorityIsEmpty updated *Form to *Authority similar to above.
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates …

Update TrustCorporateValidator bug fix

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java

https://companieshouse.atlassian.net/browse/ROE-2231
* Catching of generic exceptions was not required as these are handled by the GlobalExceptionHandler, which also returns an Internal Server Error
* Redundant unit tests and some 'throws' clauses removed
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …

ROE-2231 TL Improves exception handling within the main API controller

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeServiceTest.java

https://companieshouse.atlassian.net/browse/UAR-580
The appointmentId was missing from one of the BO change mappings in the json response for getFiling endpoint:
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits …

UAR-580: add missing appointmentId mapping for BO changes

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/CorporateManagingOfficerCessation.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/IndividualManagingOfficerCessation.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/ManagingOfficerCessation.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerCessationServiceTest.java

https://companieshouse.atlassian.net/browse/UAR-592
Add different appointmentTypes for Managing Officer Cessation so that a custom deserialiser is not needed to deserialise the objects in chips-filing-consumer service
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …

UAR-592: Add different appointmentTypes for MO Cessation

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/CorporateManagingOfficerAddition.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/IndividualManagingOfficerAddition.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/ManagingOfficerAddition.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/CorporateManagingOfficerCessation.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/cessations/IndividualManagingOfficerCessation.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/ManagingOfficerAdditionServiceTest.java

https://companieshouse.atlassian.net/browse/UAR-640
Small fix to not include empty "" for formerNames
Prefix MO appointment types with "Individual" or "Corporate". Helps with JSON de-serailization.
Both are just "Managing Officer" in CHIPS so mapping to XML with have to adjust.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …

uar-640 empty formerNames and appointmentType

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PublicDataRetrievalService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/PublicPrivateDataCombiner.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/PublicDataRetrievalServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/PublicPrivateDataCombinerTest.java

https://companieshouse.atlassian.net/browse/UAR-771
The filings service calls the public and private oe data services with an “initialize” that pulls data into those services and stores them in public getter fields. This has concurrency issues - if two or more calls are being processed at once they will each update those public fields and potentially cause the worng OE to be picked up.
```
```
- feat: a commit that introduces a new feature to the codebase (this …

uar-771 remove initialising fetch 

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelperTest.java

https://companieshouse.atlassian.net/browse/UAR-591
Extra logic needed to be added to the AddressDto / AddressApi equals in the ComparisonHelper to ensure that data wouldn't be added if only spaces and casing were changed.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …

fix/UAR-591: Change Comparison Helper to not check for casing

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/CompanyIdentificationChange.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/commonmodels/CompanyIdentification.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/OverseasEntityChangeService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/ComparisonHelper.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityChangeComparator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/CollatedOverseasEntityDataMock.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/CorporateBeneficialOwnerPscTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/commonmodels/CompanyIdentificationTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityChangeComparatorTest.java

https://companieshouse.atlassian.net/browse/UAR-917
Changes to pass register jurisdiction in json and modify the comparison logic to ensure register name and register jurisdiction  is considered equal if both of them are sent in one field
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating …

UAR-917: Send register jurisdiction in Json

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/commonmodels/Address.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntityChangeComparatorTest.java

https://companieshouse.atlassian.net/browse/UAR-960
Concatenate the premises and street in the two OE details addresses before comparison to lessen chances of changes being detected. The Public API does not break out the premises so currently a change request is always raised.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …

uar-960 oe address comparisons fix

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/UpdateSubmission.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/CorporateEntityBeneficialOwnerAddition.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/additions/IndividualBeneficialOwnerAddition.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/CorporateBeneficialOwnerPsc.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/changelist/changes/beneficialowner/psc/IndividualBeneficialOwnerPsc.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeService.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerAdditionServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/BeneficialOwnerChangeServiceTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java

https://companieshouse.atlassian.net/browse/UAR-900
https://companieshouse.atlassian.net/wiki/spaces/ROE2/pages/4234608689/Notes+for+ROE+Api+App+to+Add+Trusts+to+Update+JSON+OE02
Testing screenshots and steps:
- Ran through Update flow on UI
- Hit the filings endpoint locally
Notes:
- Assumptions for further tickets look correct
Trust data returned:
Additions flow:
- Trusts added
- No trusts added
- Additions are still being checked
- [] Tests added where applicable
```
```
- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic …

UAR-900: Tell us about trust JSON data

---

src/test/resources/overseas_entity_v_3_1.json

https://companieshouse.atlassian.net/browse/ROE-2332
The DTO and DAO classes in overseas-entities-api have to be backwards compatible with all OE submission records stored in Mongo (even the old ones). We have made some DTO and DAO changes previously and have had to add converter classes to make sure we can still convert records created using a previous version of the DTO and DAO files. To enforce this, we have created a DtoModelChangeTest unit test that converts records stored in files eg. overseas_entity_v_3_1.json.
This change is to update the overseas_entity_v_3_1.json file with the latest DTO and DAO changes introduced in teh Update journey. There are no breaking changes so no need for converter and version number changes.
We are committed to keeping commit history clean, consistent …

ROE-2332 update dto model test with update data

---

pom.xml

Move the dependency-check configuration to parent-pom and remove from application level. Also incorporates new api key parameter which allows downloads from NIST api. NIST are retiring data feeds so the key and therefore dep check up version will become necessary: https://github.com/companieshouse/parent-pom/blob/master/pom.xml#L85
```
```
- BREAKING …

Upgrade parent-pom to latest version and use its dependency-check

---

pom.xml

Reverts companieshouse/overseas-entities-api#370
OE API can't communicate with Transactions API anymore - at least when doing a GET against the API. Issue started occurring just after this change was deployed to CiDev. Exhausted all other ideas/options so want to try reverting this change next.
We can reapply once we know it's not the issue or apply with further changes if it is.

Revert "Upgrade parent-pom to latest version and use its dependency-check"

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidatorTest.java

https://companieshouse.atlassian.net/browse/UAR-1432
* Can't checked Ceased Date when running partial validation as Mongo data might be inconsistent (until all web validation on all screens has run)
* Simple check implemented
* Unit tests added and amended
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …

UAR-1432 Only check Trust Ceased Date when full validation running

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/RemoveValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/mocks/RemoveMock.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/RemoveValidatorTest.java

https://companieshouse.atlassian.net/browse/UAR-1421
* The Remove validator class can now also perform full validation
* It checks that both a filing date is NOT present and the statement field has a value of true
* Containing data blocks (update and remove) must also be present
* Refactored the OverseasEntitySubmissionDtoValidator class to also perform all the Update checks for Remove
* Unit tests added, amended and refactored to ensure all scenarios are covered
```
```
- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic …

UAR-1421 Implementation of full API validation for Remove

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingServiceTest.java

https://companieshouse.atlassian.net/browse/UAR-1465
Automatic refunds disabled for a Remove submission by omitting the 'cost' field from the filings section of the transaction.
The cost for payment is determined by the costs endpoint which is unaffected by this change.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a …

UAR-1445 Remove cost from filings for Remove to disable automatic refunds

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/Presenter.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/PopulateUpdateSubmission.java

https://companieshouse.atlassian.net/browse/ROE-2551
* JSON field name now the same as used with the Registration implementation
* Simplifies the implementation within the chips-filing-consumer, where a corresponding [change](https://github.com/companieshouse/chips-filing-consumer/pull/285) has been made
* Comment added highlighting further improvements that could be made
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR …

ROE-2551 Change Presenter 'full name' field name for Update/Remove

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesController.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/UpdateValidator.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/utils/ValidationMessages.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/controller/OverseasEntitiesControllerTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/UpdateValidatorTest.java

https://companieshouse.atlassian.net/browse/UAR-1510
* Filing date now checked against the confirmation statement next Made Up Date during partial and full validation
* Error raised if filing date is after the Made Up Date
* New method parameters added to validators in order that company profile API can be called
* Unit tests added to cover the new functionality and refactorings
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with …

UAR-1510 Implement API validation checks for next Made Up Date

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustDetailsValidatorTest.java

https://companieshouse.atlassian.net/browse/UAR-1511
* Trust validation now only checks the 'still involved?' and 'ceased date' fields if this an Update or Remove submission
* Unit tests added to verify this
```
``` …

UAR-1511 Ceased date checks not run for Registration journeys

---

spec/schema.json
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
src/test/resources/overseas_entity_v_3_2.json

https://companieshouse.atlassian.net/browse/ROE-2570
enable 'Secure-Register-Filter' field to be saved to Mongo and validate appropriately
```
```
- types …

 roe-2570 persist secure-register-filter

---

spec/schema.json
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/WhoIsRegisteringType.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dao/OverseasEntitySubmissionDao.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/dto/OverseasEntitySubmissionDto.java
src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/OverseasEntitySubmissionDtoValidatorTest.java
src/test/resources/overseas_entity_v_3_2.json

https://companieshouse.atlassian.net/browse/ROE-2598
enable 'who_is_registering' field to be saved to Mongo and validate appropriately
```
```
- types other …

roe-2598 persist who_is_registering

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidator.java
src/test/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustIndividualValidatorTest.java

https://companieshouse.atlassian.net/browse/UAR-1570
Enable the validation for trust individual 'same as residential' boolean flag and the service/correspondence address validation
It was previously only running for registration journeys as the radio/boolean for 'same as' was not being passed to the api, but that has since been fixed by https://companieshouse.atlassian.net/browse/UAR-1547 and so is now available to be validated.
```
```
- feat: a commit that introduces …

UAR-1570 Enable trust individual 'same as residential address' and correspondence address validation

---

Tiltfile.dev

NA
The Docker image name has been updated with the Java 21 upgrade and tiltfile needs the same name to run in docker or you will get startup problems using tilt.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits …

Update tiltfile with new image name

---

src/main/java/uk/gov/companieshouse/overseasentitiesapi/validation/TrustCorporateValidator.java

https://companieshouse.atlassian.net/browse/ROE-2630
Removed API validation that did not match the web validation and was therefore causing a 400 error to be returned to the web. 
This validation was specific to Legal Entity 'Interested persons' who had an 'interested date' before the 'trust creation date' on the Registration journey. i.e. It does not exist for Individual 'Interested persons' on Registration or any 'Interested persons' on Update or Remove. It doesn't seem to be in any acceptance criteria.
```
```
- fix: a commit that patches a bug in your codebase (this …

ROE-2630 Bug Fix Remove API validation not on the web journey

---

Tiltfile.dev

N/A
Development mode ws not picking up changes due to the image name not matching the docker image name in Tiltfile.dev
```
``` …

Fix development mode i image name in Tiltfile.dev
